### ISSUE TITLE
Ghost 2.x post content is missing after migration

### ISSUE THREAD

**Issue by docrinehart** [lmammino/ghost2hexo#6]
... Ghost moved from markdown to the mobiledoc format. I inspected the json, and there's actually 3 available properties for the content in my case. Mobiledoc, html, and plaintext. I replaced the content propery with html and at a glance everything seemed to come over fine. I was going to take a closer look this afternoon or Monday morning to inspect each post.

That said, html markup isn't ideal but is usable as-is. A better option might be to look at mobiledoc to markdown processing, I think there's a library that can do this already from my initial searches, but I haven't dug further yet.

~Doc

_Originally posted by @docrinehart in https://github.com/lmammino/ghost2hexo/issues/1#issuecomment-455883814_

**Comment by lmammino** [comment]
Closed by #5
